# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.IntegerField()),
                ('date_assigned', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('bottle_size', models.DecimalField(decimal_places=3, max_digits=5)),
                ('bottles_per_case', models.IntegerField()),
                ('proof', models.DecimalField(decimal_places=2, max_digits=5)),
                ('number_of_cases', models.IntegerField()),
                ('stray_bottles', models.IntegerField(blank=True, null=True)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wine_gallons', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proof_gallons', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_removed', models.DateField(blank=True, null=True)),
                ('invoice_number', models.IntegerField(blank=True, null=True)),
                ('proof_gallons_removed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
