# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='case_fraction',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=5),
        ),
    ]
