# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='producted_type',
            new_name='product_type',
        ),
    ]
