# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20170212_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='invoice_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
