# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20170212_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Product'),
        ),
    ]
