# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20170213_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='bottle_size',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='bottles_per_case',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
