# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20170213_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='product',
        ),
    ]
