# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_inventoryitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='date_assigned',
            field=models.DateField(auto_now_add=True),
        ),
    ]
