# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20170213_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='invoice_number',
        ),
    ]
