# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20170220_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('proof', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='invoice_number',
            new_name='product_number',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='stray_bottles',
        ),
        migrations.AddField(
            model_name='stray',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Product'),
        ),
    ]
