# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20170220_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='stray',
            name='bottle_size',
            field=models.DecimalField(decimal_places=3, default=0.375, max_digits=3),
            preserve_default=False,
        ),
    ]
