# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_stray_bottle_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='bottles_per_case',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='bottle_size',
            field=models.DecimalField(decimal_places=3, default=0.375, max_digits=3),
            preserve_default=False,
        ),
    ]
