# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20170220_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='bottle_size',
        ),
        migrations.AddField(
            model_name='product',
            name='bottle_size',
            field=models.DecimalField(decimal_places=3, default=0.375, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='case_number',
            field=models.IntegerField(unique=True),
        ),
    ]
