# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20170221_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stray',
            name='bottle_size',
        ),
    ]
