# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20170221_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bottle_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
