# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_product_bottle_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='UPC',
            field=models.CharField(max_length=20),
        ),
    ]
