# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20170222_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='number_of_cases',
        ),
    ]
