# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_inventoryitem_number_of_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stray',
            name='date_assigned',
            field=models.DateField(),
        ),
    ]
