# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20170222_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
