# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
