# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20170227_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Destination',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='location',
            new_name='destination',
        ),
    ]
